algoritmo "idade"
// Função :
// Autor :
// Data : 09/09/2019
// Seção de Declarações 
var
 idade: inteiro
inicio
      escreva ("informe sua idade: ")
      leia (idade)
      se (idade <=10) entao
         escreva ("infantil")
      fimse
      se (idade > 10) e (idade <= 17) entao
         escreva ("juvenil")
      fimse
      se (idade > 17) entao
         escreva ("senior")
      fimse
fimalgoritmo
