Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2019
Var
// Seção de Declarações das variáveis 
numero: real
dobro: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("escreva o numero")
   leia (numero)
   escreval ("o dobro é: ", numero*2)


Fimalgoritmo